first pull request
romrell4/tennis-ladder-ios pull request #4
Opened 2018-12-27 00:55 UTC by powerpufffs

2018-12-27 01:49 UTC, romrell4 requested changes
> Reviewed 8 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 8 of 12 files reviewed, 24 unresolved discussions (waiting on @powerpufffs)

___
*[Podfile, line 11 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhHNVd94e09mnF9K7a:-LUhHNVe-eN_Un784eWl:bn5iwep) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/Podfile#L11)):*
> ```Ruby
>   pod 'Alamofire', '~> 4.8.0'
>   pod 'moa', '~> 10.0'
>   pod 'Firebase'
> ```

Do we need to pull in Firebase explicitly? I thought that the FirebaseUI and Core already had information about the user...
___
*[TennisLadder/GoogleService-Info.plist, line 1 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhHZJK2yEPIqVijmWB:-LUhHZJK2yEPIqVijmWC:bukhdgb) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/GoogleService-Info.plist#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

Shoot. This file is supposed to be gitignored... there are some sensitive keys in here that we don’t want getting out. Can you make sure that you remove this? Your gitignore file include this already.
___
*[TennisLadder.xcodeproj/project.pbxproj, line 619 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI83qAj1rFquPuv-k:-LUhI83qAj1rFquPuv-l:btus5os) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L619)):*
> ```
> 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
> 				CODE_SIGN_STYLE = Automatic;
> 				DEVELOPMENT_TEAM = TN3XLNWBJ8;
> ```

Did you change this on purpose? If not, let’s change it back and see if it works
___
*[TennisLadder.xcodeproj/project.pbxproj, line 627 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI0qT9ZJcWmSA5Wth:-LUhI0qT9ZJcWmSA5Wti:bf3fg09) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L627)):*
> ```
> 				PRODUCT_BUNDLE_IDENTIFIER = "com.romrell4.tennis-ladder";
> 				PRODUCT_NAME = "$(TARGET_NAME)";
> 				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
> ```

Do you know what this line is? I don’t think we want it, but if you added it on purpose, tell me about it
___
*[TennisLadder.xcodeproj/project.pbxproj, line 639 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIE9C-2QTe3tD9f7B:-LUhIE9C-2QTe3tD9f7C:b-34vmyd) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L639)):*
> ```
> 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
> 				CODE_SIGN_STYLE = Automatic;
> 				DEVELOPMENT_TEAM = TN3XLNWBJ8;
> ```

See above
___
*[TennisLadder.xcodeproj/project.pbxproj, line 647 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIFnfE9nZtJOY-fid:-LUhIFnfE9nZtJOY-fie:b-34vmyd) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L647)):*
> ```
> 				PRODUCT_BUNDLE_IDENTIFIER = "com.romrell4.tennis-ladder";
> 				PRODUCT_NAME = "$(TARGET_NAME)";
> 				SWIFT_OPTIMIZATION_LEVEL = "-Onone";
> ```

See above
___
*[TennisLadder/Controller/AddMatchViewController.swift, line 2 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIKQ40nA0Azv1QEmE:-LUhIKQ40nA0Azv1QEmF:b-dqzll1) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/AddMatchViewController.swift#L2)):*
> ```Swift
> //
> //  AddMatchViewController.swift
> ```

What is this? Is this the ReportMatchViewController? If so, can we rename it?
___
*[TennisLadder/Controller/LadderViewController.swift, line 46 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIiWf1OdT7eY1w2jW:-LUhIiWf1OdT7eY1w2jX:b-4g6kyc) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/LadderViewController.swift#L46)):*
> ```Swift
>             let vc = segue.destination as? ReportMatchViewController,
>             let player = sender as? Player {
>             //TODO: figure out which player belongs to who
> ```

What do you mean by this TODO? In android the player on the left is always the logged in player and the other is the one that they tapped on
___
*[TennisLadder/Controller/LadderViewController.swift, line 59 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJ2M28MK3Bqtily3m:-LUhJ2M28MK3Bqtily3n:b-84ir6r) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/LadderViewController.swift#L59)):*
> ```Swift
>     
>     func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
>         let cell = tableView.dequeueReusableCell(withIdentifier: "PlayerCell", for: indexPath)
> ```

Let’s change the identifier to “cell” and use the default extension (see how I did it in the previous CC)
___
*[TennisLadder/Controller/MainViewController.swift, line 21 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJR4B-ViUMBh85ORL:-LUhJR4C5m_Opt_cTAiL:b-89lft6) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/MainViewController.swift#L21)):*
> ```Swift
> 	@IBOutlet private weak var statusLabel: UILabel!
> 	@IBOutlet private weak var spinner: UIActivityIndicatorView!
>     @IBOutlet var tableView: UITableView!
> ```

Make private if you can
___
*[TennisLadder/Controller/PlayerViewController.swift, line 2 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJZDH8uHOYNLXE9QW:-LUhJZDH8uHOYNLXE9QX:buhuizq) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L2)):*
> ```Swift
> //
> //  DetailViewController.swift
> ```

Change this comment as well to reflect the new name
___
*[TennisLadder/Controller/PlayerViewController.swift, line 9 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJd_22p9ihQOvgcx5:-LUhJd_22p9ihQOvgcx6:b2ji7tg) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L9)):*
> ```Swift
> //
> 
> import Foundation
> ```

I don’t think you need foundation... I think UIKit transitively pulls it in. Try removing it
___
*[TennisLadder/Controller/PlayerViewController.swift, line 13 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJm3LAn-Vq6zTy_bs:-LUhJm3LAn-Vq6zTy_bt:boxct0r) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L13)):*
> ```Swift
> import moa
> 
> private let DATE_FORMATTTER = DateFormatter.defaultDateFormat("dd/MM/yyyy")
> ```

What do you use this date formatted for? I don’t remember displaying any dates on this page...
___
*[TennisLadder/Controller/PlayerViewController.swift, line 23 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJw-X8vaMyelQayXm:-LUhJw-X8vaMyelQayXn:b-9hhb8j) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L23)):*
> ```Swift
>     
>     //MARK: Outlets
>     @IBOutlet var playerImage: UIImageView!
> ```

Make all of these private if possible
___
*[TennisLadder/Controller/PlayerViewController.swift, line 25 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhKsqU2UKg063WN_hi:-LUhKsqU2UKg063WN_hj:b9pnzto) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLad [...]

2018-12-27 02:07 UTC, powerpufffs commented
___
*[TennisLadder.xcodeproj/project.pbxproj, line 619 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI83qAj1rFquPuv-k:-LUhNnMQAGjXyZBtJCst:b-blu3ed) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L619)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Did you change this on purpose? If not, let’s change it back and see if it works
</blockquote></details>

I might have changed it today by accident. I spent a lot of time trying to resolve silly XIB and NIB problems. It involved tweaking the package content files.... How do I see the original?


<!-- Sent from Reviewable.io -->

2018-12-27 04:39 UTC, romrell4 requested changes
> Reviewed 4 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 59 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder.xcodeproj/project.pbxproj, line 619 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI83qAj1rFquPuv-k:-LUhqa5_01IYtgzXWFp8:bburaly) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L619)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

I might have changed it today by accident. I spent a lot of time trying to resolve silly XIB and NIB problems. It involved tweaking the package content files.... How do I see the original?
</blockquote></details>

At the top of each file in this review, you'll see a "matrix" (a few boxes in a line). Each of these represents a "revision" (or a push). At the top of each comment, you can see which revision this comment started on (for instance, this one should say "r1"). If you click on the "r1", it should take you back to the diff with the original commit. If that doesn't work, you can click on the first (left most) box in the matrix, and it should show you the diff of the current revision with the first one (which should show you the old value)
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 12 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhrreg2ngsDFOro6u2:-LUhrreg2ngsDFOro6u3:b-g7xyv4) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L12)):*
> ```Swift
> import moa
> 
> class ReportMatchViewController: UIViewController, UIPickerViewDelegate, UIPickerViewDataSource {
> ```

Instead of the VC being the delegate, can we just use the textboxes with picker accessory views? I think there are a number of instances where we do this in the BYU app, so it would be good to learn how to do it :)
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 14 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhsJ4rEQLvN3csurfQ:-LUhsJ4rEQLvN3csurfR:b-sqi2m5) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L14)):*
> ```Swift
> class ReportMatchViewController: UIViewController, UIPickerViewDelegate, UIPickerViewDataSource {
>     //MARK: Public Properties
>     var playerOne : Player!
> ```

Our team's style guide doesn't put spaces after variables before the type declaration. Remove the space here (and anywhere else where you find it)
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 18 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhrJ7pD5ZS0xwkOlQ-:-LUhrJ7pD5ZS0xwkOlQ0:br83dcx) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L18)):*
> ```Swift
>     
>     //MARK: Private Properties
>     private var possibleScores = [0, 1, 2, 3, 4, 5, 6, 7]
> ```

In swift, I think you can do this with a simple `1...7` (not sure if that's the exact right syntax, but you can google if that doesn't work :)
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 19 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhrSIF4AUVyCWkJwRB:-LUhrSIF4AUVyCWkJwRC:bhrwb7y) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L19)):*
> ```Swift
>     //MARK: Private Properties
>     private var possibleScores = [0, 1, 2, 3, 4, 5, 6, 7]
>     private var scores = [0, 0, 0, 0, 0, 0, 0]
> ```

Why are you saving these as an array? Why not just save them in a `Match` object? (since that's what will need to hold them in the end anyways)
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 22 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhraaJAGEr6T7PY3z_:-LUhraaJAGEr6T7PY3za:b-xyykdp) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L22)):*
> ```Swift
>     
>     //MARK: Outlets
>     @IBOutlet var playerOneImage: UIImageView!
> ```

Make all of these private (if they can be). Also, normally `IBOutlet`s are `weak`. Any idea why yours aren't? If not, let's make them weak (see the MainVC for examples)
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 37 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhrm2263Eu-NCUAqhc:-LUhrm2263Eu-NCUAqhd:byd78bn) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L37)):*
> ```Swift
>     override func viewDidLoad() {
>         super.viewDidLoad()
>         var player = playerOne
> ```

This line doesn't seem to do anything...
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 38 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhsW0B-g5cDu8mvYrZ:-LUhsW0B-g5cDu8mvYr_:b-dlekz0) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L38)):*
> ```Swift
>         super.viewDidLoad()
>         var player = playerOne
>         var pickers = [
> ```

This line doesn't seem to do anything either...
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 50 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhsdD81VWvWvVektCF:-LUhsdD99rgSxUJCFCcm:b-h87n92) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L50)):*
> ```Swift
>     
>     func setUpViews() {
>         if let playOne = playerOne {
> ```

You shouldn't need the `if let`. `playerOne` is already non-optional.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 55 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhsiMa8NRAroRdC_R2:-LUhsiMa8NRAroRdC_R3:b-ctrph2) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L55)):*
> ```Swift
>         }
>         
>         if let playTwo = playerTwo {
> ```

See above comment
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 61 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhsp6I8v1O9-Z0ka7d:-LUhsp6I8v1O9-Z0ka7e:b1olraa) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L61)):*
> ```Swift
>     }
>     
>     func numberOfComponents(in matchOnePV: UIPickerView) -> Int {
> ```

This variable name is misleading. I might go back to just pickerView.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 61 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhsvQT5AOgcqLpFNz7:-LUhsvQT5AOgcqLpFNz8:b-j88tt1) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L61)):*
> ```Swift
>     }
>     
>     func numberOfComponents(in matchOnePV: UIPickerView) -> Int {
> ```

I think this might default to 1... You might be able to remove this function altogether.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 73 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUht3tk8ljNPAczP3ix:-LUht3tk8ljNPAczP3iy:b-aoi6j6) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eea [...]

2018-12-27 16:52 UTC, powerpufffs reviewed
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 59 unresolved discussions (waiting on @romrell4 and @powerpufffs)

___
*[Podfile, line 11 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhHNVd94e09mnF9K7a:-LUkG_MS49_23rumnwpi:bb5lv7g) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/Podfile#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we need to pull in Firebase explicitly? I thought that the FirebaseUI and Core already had information about the user...
</blockquote></details>

I tried pulling it out but then FirebaseApp in the appdelegate isn't recognized anymore.
___
*[TennisLadder/GoogleService-Info.plist, line 1 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhHZJK2yEPIqVijmWB:-LUkHLnlA5QT941iFfE4:bv5y7b3) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/GoogleService-Info.plist#L1)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Shoot. This file is supposed to be gitignored... there are some sensitive keys in here that we don’t want getting out. Can you make sure that you remove this? Your gitignore file include this already.
</blockquote></details>

I've looked around for a gitignore file but can't seem to find one. Where would it usually be?
___
*[TennisLadder.xcodeproj/project.pbxproj, line 619 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI83qAj1rFquPuv-k:-LUkI27GE8I4e4q_YqDu:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L619)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

At the top of each file in this review, you'll see a "matrix" (a few boxes in a line). Each of these represents a "revision" (or a push). At the top of each comment, you can see which revision this comment started on (for instance, this one should say "r1"). If you click on the "r1", it should take you back to the diff with the original commit. If that doesn't work, you can click on the first (left most) box in the matrix, and it should show you the diff of the current revision with the first one (which should show you the old value)
</blockquote></details>

Done.
___
*[TennisLadder.xcodeproj/project.pbxproj, line 627 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI0qT9ZJcWmSA5Wth:-LUhO5IS68ZpYjrTQoEe:b-mv3jn) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L627)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do you know what this line is? I don’t think we want it, but if you added it on purpose, tell me about it
</blockquote></details>

I was having some major file trouble and this was one line that seemed to help. Now that everything is up and working again, we might not need it. I had to add this to get my breakpoints to work.
___
*[TennisLadder.xcodeproj/project.pbxproj, line 639 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIE9C-2QTe3tD9f7B:-LUhPqXL-aHeXOrpby4n:b459pc7) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L639)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Not sure. Again, it was probably something to do with all the changes I had to make to get everything to compile again. I'll try to go back
___
*[TennisLadder/Controller/AddMatchViewController.swift, line 2 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIKQ40nA0Azv1QEmE:-LUhOOiTC1_KlFN4jeiG:b8elg33) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/AddMatchViewController.swift#L2)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What is this? Is this the ReportMatchViewController? If so, can we rename it?
</blockquote></details>

That file should be gone...it wasn't showing up on Xcode. But it's deleted now. 
___
*[TennisLadder/Controller/LadderViewController.swift, line 46 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIiWf1OdT7eY1w2jW:-LUhQL705MoFxZFP4rH7:b-7ikmkq) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/LadderViewController.swift#L46)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What do you mean by this TODO? In android the player on the left is always the logged in player and the other is the one that they tapped on
</blockquote></details>

Thanks for the clarification. I wasn't sure. Just wanted to put something there as a reminder for tomorrow.
___
*[TennisLadder/Controller/LadderViewController.swift, line 59 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJ2M28MK3Bqtily3m:-LUhQRbzCMaZKoCTEd35:bkhuo2m) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/LadderViewController.swift#L59)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let’s change the identifier to “cell” and use the default extension (see how I did it in the previous CC)
</blockquote></details>

Changed the identifier. Not sure what extensions you are referring to though.
___
*[TennisLadder/Controller/MainViewController.swift, line 21 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJR4B-ViUMBh85ORL:-LUhQbWOCwM4nmD12ci2:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/MainViewController.swift#L21)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Make private if you can
</blockquote></details>

Done.
___
*[TennisLadder/Controller/PlayerViewController.swift, line 2 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJZDH8uHOYNLXE9QW:-LUhQoPG6xU0RH-_MYma:bf5lczx) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L2)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Change this comment as well to reflect the new name
</blockquote></details>

Done. Renamed the others as well.
___
*[TennisLadder/Controller/PlayerViewController.swift, line 9 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJd_22p9ihQOvgcx5:-LUhQwPI5rmLM44EEDXU:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L9)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I don’t think you need foundation... I think UIKit transitively pulls it in. Try removing it
</blockquote></details>

Done.
___
*[TennisLadder/Controller/PlayerViewController.swift, line 13 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJm3LAn-Vq6zTy_bs:-LUhP7EA7-ZNe_Z7Ijdm:buhfwo6) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L13)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What do you use this date formatted for? I don’t remember displaying any dates on this page...
</blockquote></details>

this was something you typed up! I can't remember for wha [...]

2018-12-27 18:12 UTC, romrell4 requested changes
> Reviewed 4 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 7 of 11 files reviewed, 53 unresolved discussions (waiting on @romrell4 and @powerpufffs)

___
*[Podfile, line 11 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhHNVd94e09mnF9K7a:-LUkkVhx6d5AdmQzCJBv:b-9vth47) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/Podfile#L11)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

I tried pulling it out but then FirebaseApp in the appdelegate isn't recognized anymore.
</blockquote></details>

Work with me on this one. It's working on master without it
___
*[TennisLadder/GoogleService-Info.plist, line 1 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhHZJK2yEPIqVijmWB:-LUkkNtgAeV-tTBof8Em:bmw7ak0) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/GoogleService-Info.plist#L1)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

I've looked around for a gitignore file but can't seem to find one. Where would it usually be?
</blockquote></details>

In the very top level folder of the git repo `~/SourceCode/tennis-ladder-ios`
___
*[TennisLadder.xcodeproj/project.pbxproj, line 619 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI83qAj1rFquPuv-k:-LUkmn4gAeaJxNVtEBKI:b-uzhpsx) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L619)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any change here... Did you revert it?
___
*[TennisLadder.xcodeproj/project.pbxproj, line 627 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI0qT9ZJcWmSA5Wth:-LUkmrjb2F2uvhh4DTrg:b7f12jd) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L627)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

I was having some major file trouble and this was one line that seemed to help. Now that everything is up and working again, we might not need it. I had to add this to get my breakpoints to work.
</blockquote></details>

This just optimizes the swift code when it compiles. We shouldn't need this. Remove it before marking this comment as done
___
*[TennisLadder.xcodeproj/project.pbxproj, line 639 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIE9C-2QTe3tD9f7B:-LUkn2cb9VuS5qeF6yaG:b4ms89k) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L639)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Not sure. Again, it was probably something to do with all the changes I had to make to get everything to compile again. I'll try to go back
</blockquote></details>

Try reverting before commenting again
___
*[TennisLadder.xcodeproj/project.pbxproj, line 430 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkmYbj-WtZ6gxavbr9:-LUkmYbj-WtZ6gxavbrA:bgbd2wo) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder.xcodeproj/project.pbxproj#L430)):*
> ```
> 			files = (
> 				0CD92EC321C15F8500480763 /* LadderViewController.swift in Sources */,
> 				0CD92EC921C15F8500480763 /* Tennis.xcdatamodeld in Sources */,
> ```

Uh oh. Is this something that we missed when renaming the project? Can this file get removed entirely? Search the rest of the this for files called just "Tennis" to see if we missed anything else
___
*[TennisLadder/Controller/LadderViewController.swift, line 46 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIiWf1OdT7eY1w2jW:-LUkonSe4RG9A5e6wtKI:b-80h2ie) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/LadderViewController.swift#L46)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Thanks for the clarification. I wasn't sure. Just wanted to put something there as a reminder for tomorrow.
</blockquote></details>

Sounds good. Resolve before commenting again
___
*[TennisLadder/Controller/LadderViewController.swift, line 59 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJ2M28MK3Bqtily3m:-LUkorC54KFuDbwECCO2:bp226m6) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/LadderViewController.swift#L59)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Changed the identifier. Not sure what extensions you are referring to though.
</blockquote></details>

Look at how I dequeue my cell in the MainVC
___
*[TennisLadder/Controller/LadderViewController.swift, line 63 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkovih-J0ZKf9I5G5Z:-LUkovih-J0ZKf9I5G5_:b-wajmf0) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/LadderViewController.swift#L63)):*
> ```Swift
>         if let cell = cell as? PlayerCell {
>             let player = players[indexPath.row]
>             cell.name.text = player.name
> ```

By removing this stuff, won't is not work anymore? Did you mean to have `cell.player = players[indexPath.row]`?
___
*[TennisLadder/Controller/PlayerViewController.swift, line 34 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhKFky2i8RKOPDjwfz:-LUkpHgl9wQI4yvlhtv4:bb9hrzn) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L34)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

ahh. I tried to remove it earlier today, but it didn't like it: "Value of optional type 'Player?' must be unwrapped to refer to member 'userId' of wrapped base type 'Player'"- 
</blockquote></details>

Super weird! It does that for me to! Oh. Got it. The issue is that the getMatches function takes two Ints. Just change the second one to a String. That was a really dumb error message from Xcode...
___
*[TennisLadder/Controller/PlayerViewController.swift, line 41 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhKTyVDq2a5kZ70-2a:-LUkqCpsE6t5Le6ZfPqZ:b-jxvu5p) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L41)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Not sure what you mean.
</blockquote></details>

Check in the MainVC for how I handle errors from the web service, and do that here (and any other place you make web requests)
___
*[TennisLadder/Controller/PlayerViewController.swift, line 63 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhLWHcA7N2yM-i4RGS:-LUkqsc90RCLS2Bv3haU:b-f4ehr5) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L63)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You’ll need to handle third sets as well.
</blockquote></details>

Now that you moved this logic into the cell, I'll move this comment as well
___
*[TennisLadder/Controller/PlayerViewController.swift, line 42 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkqLpS7NWRryK4CYLL:-LUkqLpS7NWRryK4CYLM:b-bulqhl) ([raw file](https://github.com/romrell4/te [...]

2018-12-27 21:05 UTC, romrell4 requested changes
> Reviewed 2 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 7 of 11 files reviewed, 55 unresolved discussions (waiting on @romrell4 and @powerpufffs)

___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 19 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhrSIF4AUVyCWkJwRB:-LUlSkHEDFcJZIJtUPCv:bq78mrh) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L19)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

okay! How are the ladderIds generated?
</blockquote></details>

What do you mean by that? You should have a ladder (the player objects know which ladderId they are in)
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 22 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhraaJAGEr6T7PY3z_:-LUlTBkWDRMhrwxUc3SP:bon74x8) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L22)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Those are just what comes up when I make the connection. What is the main difference between weak and strong connection?
</blockquote></details>

Interesting. Mine always makes them weak. Let’s look at this tomorrow. You can google the difference between strong (default) and weak
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 20 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlS_DJ2a1gE0ng8OXc:-LUlS_DJ2a1gE0ng8OXd:b68x5fq) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L20)):*
> ```Swift
>     var currentPlayer: Player!
>     var opponentPlayer: Player!
>     var matches: [Match]!
> ```

Shouldn’t this be private?
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 28 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlSzq-0maOUCFogyye:-LUlSzq-0maOUCFogyyf:bdom7vy) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L28)):*
> ```Swift
>     private var scores = [0, 0, 0, 0, 0, 0, 0]
>     private var picker1 = UIPickerView()
>     private var picker2 = UIPickerView()
> ```

Do we need to save these as well as the text fields? I thought we’d only need to save the text fields as Class level variables
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 35 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlTPmoEKPKaxHkxeef:-LUlTPmoEKPKaxHkxeeg:blw89qo) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L35)):*
> ```Swift
>     
>     //MARK: Outlets
>     @IBOutlet private weak var match1LoserScoreTextField: UITextField!
> ```

Good names. However, these are set scores, not match scores. Let’s renamed these set1LoserTextField etc. also, organize them from left to right (set1winner, set1loser, set2winner, etc)
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 49 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlTrdO03Jn3zNa0YYv:-LUlTrdO03Jn3zNa0YYw:bg897f0) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L49)):*
> ```Swift
>         setUpViews()
>         
>         let pickers = [picker1, picker2, picker3, picker4, picker5, picker6]
> ```

Why do you pass this in if they’re already class level variables? Can’t you just do this in the function?
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 52 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlTzs48eINW-cDHwPv:-LUlTzs48eINW-cDHwPw:b-lp4pjy) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L52)):*
> ```Swift
>         setUpPickers(pickers)
>         
>         let tap: UITapGestureRecognizer = UITapGestureRecognizer(target: self, action: #selector(UIInputViewController.dismissKeyboard))
> ```

I think there’s a way to do this without a gesture... let’s look at this tomorrow


<!-- Sent from Reviewable.io -->

2018-12-28 14:31 UTC, romrell4 requested changes
> Reviewed 2 of 9 files at r4.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 5 of 13 files reviewed, 58 unresolved discussions (waiting on @romrell4 and @powerpufffs)

___
*[.DS_Store, line 0 at r4](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpBHYt7NE_Pzsxv1AL:-LUpBHYt7NE_Pzsxv1AM:bepyl1i) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/fe14270b696e4cfa7919c08c4c8ab1aaea221b1f/.DS_Store#L0)):*
This should be gitignored. Remove it from git and add to the .gitignore file
___
*[TennisLadder/.DS_Store, line 0 at r4](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpBcenEHNeRxIsptVQ:-LUpBcenEHNeRxIsptVR:bfcm71g) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/fe14270b696e4cfa7919c08c4c8ab1aaea221b1f/TennisLadder/.DS_Store#L0)):*
See above. Also, in the future, only commit stuff if you know what it is. We’ve had issues where credentials were leaked because someone didn’t check all of their files before committing and it cost BYU thousands of dollars. This one’s not a big deal at all, but the principle is important
___
*[TennisLadder.xcodeproj/project.pbxproj, line 22 at r4](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpC3NT67jCIoDvvyoV:-LUpC3NT67jCIoDvvyoW:b-xw19sv) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/fe14270b696e4cfa7919c08c4c8ab1aaea221b1f/TennisLadder.xcodeproj/project.pbxproj#L22)):*
> ```
> 		0CD92EE421C15F8600480763 /* TennisUITests.swift in Sources */ = {isa = PBXBuildFile; fileRef = 0CD92EE321C15F8600480763 /* TennisUITests.swift */; };
> 		0CD92EF521C160B000480763 /* MainViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 0CD92EF421C160B000480763 /* MainViewController.swift */; };
> 		0CD92EF721C160CC00480763 /* DetailViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 0CD92EF621C160CC00480763 /* DetailViewController.swift */; };
> ```

Wait... why did we go back to the old names? Was this on purpose?


<!-- Sent from Reviewable.io -->

2018-12-28 16:19 UTC, powerpufffs reviewed
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 4 of 14 files reviewed, 58 unresolved discussions (waiting on @romrell4 and @powerpufffs)

___
*[TennisLadder.xcodeproj/project.pbxproj, line 619 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI83qAj1rFquPuv-k:-LUm6Inn-DRHx89NoeTu:bt2vr0y) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L619)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I don't see any change here... Did you revert it?
</blockquote></details>

Fixed!
___
*[TennisLadder.xcodeproj/project.pbxproj, line 639 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIE9C-2QTe3tD9f7B:-LUpXIXQD5duIyEDvn12:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L639)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Try reverting before commenting again
</blockquote></details>

Done.
___
*[TennisLadder.xcodeproj/project.pbxproj, line 647 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIFnfE9nZtJOY-fid:-LUpYLDcDhEpmwR0Zwy7:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L647)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[TennisLadder/Controller/LadderViewController.swift, line 59 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhJ2M28MK3Bqtily3m:-LUm9ipj3KbbSaWJop87:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/LadderViewController.swift#L59)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Look at how I dequeue my cell in the MainVC
</blockquote></details>

Done.
___
*[TennisLadder/Controller/LadderViewController.swift, line 63 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkovih-J0ZKf9I5G5Z:-LUpaylaBRq4uUStzWtR:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/LadderViewController.swift#L63)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

By removing this stuff, won't is not work anymore? Did you mean to have `cell.player = players[indexPath.row]`?
</blockquote></details>

Done.
___
*[TennisLadder/Controller/PlayerViewController.swift, line 34 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhKFky2i8RKOPDjwfz:-LUpb-3GEvHnayHemiH1:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L34)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Super weird! It does that for me to! Oh. Got it. The issue is that the getMatches function takes two Ints. Just change the second one to a String. That was a really dumb error message from Xcode...
</blockquote></details>

Done.
___
*[TennisLadder/Controller/PlayerViewController.swift, line 41 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhKTyVDq2a5kZ70-2a:-LUmGC1f735bLzpNXueO:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L41)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Check in the MainVC for how I handle errors from the web service, and do that here (and any other place you make web requests)
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 18 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhrJ7pD5ZS0xwkOlQ-:-LUmNJrq8NWDZwQhZTRp:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

In swift, I think you can do this with a simple `1...7` (not sure if that's the exact right syntax, but you can google if that doesn't work :)
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 20 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlS_DJ2a1gE0ng8OXc:-LUmNGKW5jY0iA0WY8_Y:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L20)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Shouldn’t this be private?
</blockquote></details>

Done.
___
*[TennisLadder/View/MatchTableViewCell.swift, line 18 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkr3YdDNCzK2wXAXFN:-LUmUAOH0qrlBw0EWaFT:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder/View/MatchTableViewCell.swift#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

You’ll need to handle third sets as well.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-28 16:21 UTC, powerpufffs commented
___
*[TennisLadder.xcodeproj/project.pbxproj, line 22 at r4](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpC3NT67jCIoDvvyoV:-LUpbcXGD6UoX2SyyTci:b-vrt26h) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/fe14270b696e4cfa7919c08c4c8ab1aaea221b1f/TennisLadder.xcodeproj/project.pbxproj#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Wait... why did we go back to the old names? Was this on purpose?
</blockquote></details>

No longer there when I checked. done


<!-- Sent from Reviewable.io -->

2018-12-28 16:21 UTC, romrell4 requested changes
> Reviewed 2 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 6 of 14 files reviewed, 58 unresolved discussions (waiting on @romrell4 and @powerpufffs)

___
*[TennisLadder/.DS_Store, line  at r4](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpBcenEHNeRxIsptVQ:-LUpb_xD573YCxklX_5S:b-f0cfev) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/fe14270b696e4cfa7919c08c4c8ab1aaea221b1f/TennisLadder/.DS_Store#L)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

See above. Also, in the future, only commit stuff if you know what it is. We’ve had issues where credentials were leaked because someone didn’t check all of their files before committing and it cost BYU thousands of dollars. This one’s not a big deal at all, but the principle is important
</blockquote></details>

It looks like you added it to your gitignore properly, but you didn't git rm all the ones that were already committed. Can you do that? (when you're done, this file should be gone). Also, look for any others that might have been committed


<!-- Sent from Reviewable.io -->

2018-12-28 16:46 UTC, romrell4 requested changes
> Reviewed 4 of 11 files at r2, 1 of 5 files at r3, 4 of 9 files at r4, 3 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 41 unresolved discussions (waiting on @powerpufffs and @romrell4)

___
*[TennisLadder.xcodeproj/project.pbxproj, line 619 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI83qAj1rFquPuv-k:-LUpcN_J9kdUjR6Ga2LT:bel1wor) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L619)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Fixed!
</blockquote></details>

It still looks unchanged. The code on master has `G9JN5J3VZ9`. Work with me on this one
___
*[TennisLadder.xcodeproj/project.pbxproj, line 627 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI0qT9ZJcWmSA5Wth:-LUpcZNF28n9ZrNVYh52:bvl15tp) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L627)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This just optimizes the swift code when it compiles. We shouldn't need this. Remove it before marking this comment as done
</blockquote></details>

I think this is the one that you meant to mark as done. It looks like you removed the SWIFT compiler flag. Mark this one as done
___
*[TennisLadder.xcodeproj/project.pbxproj, line 639 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIE9C-2QTe3tD9f7B:-LUpciC4-puR_BUAk54L:b-nygam) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L639)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still not done. Work me with on this one
___
*[TennisLadder.xcodeproj/project.pbxproj, line 617 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpcG567SrriLRW8jN-:-LUpcG567SrriLRW8jN0:b6uiktx) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder.xcodeproj/project.pbxproj#L617)):*
> ```
> 			baseConfigurationReference = 4F9180E292F5EBAC27967091 /* Pods-TennisLadder.debug.xcconfig */;
> 			buildSettings = {
> 				ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;
> ```

Was this added on purpose? Is there a reason why we need it?
___
*[TennisLadder.xcodeproj/project.pbxproj, line 637 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpcgR5AZo6xBDreTCI:-LUpcgR5AZo6xBDreTCJ:b-34vmyd) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder.xcodeproj/project.pbxproj#L637)):*
> ```
> 			baseConfigurationReference = D4E4BB323CF0F78FCE102409 /* Pods-TennisLadder.release.xcconfig */;
> 			buildSettings = {
> 				ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES;
> ```

See above
___
*[TennisLadder/Controller/PlayerViewController.swift, line 42 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkqLpS7NWRryK4CYLL:-LUpcscd-Cxr-mvFFxu5:bxprfnm) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder/Controller/PlayerViewController.swift#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why did you add this? Is this so that the matches will load after a new match was reported? If so, we can do that with an unwind segue (I'll have to show you that in person, so wait for me to be in the office and ask me about this one).

As an aside, you would probably want to use viewWillAppear here instead of viewDidAppear, so that the user doesn't see the table reload. Unless that's what you were going for
</blockquote></details>

Great. We'll still see if we can replace this with unwind segues. Google around to learn what unwind segues are, and let me know if you have any questions. I can help you with this today if you'd like
___
*[TennisLadder/Controller/PlayerViewController.swift, line 57 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkqm9p96kUAShmDt8D:-LUpd7u00CvFWiZLCY1b:b-n2k7vx) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder/Controller/PlayerViewController.swift#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use extension (see MainVC)
</blockquote></details>

This looks out of date. Mark this as done
___
*[TennisLadder/Controller/PlayerViewController.swift, line 45 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpd3hE8kHSxGjeKtC9:-LUpd3hE8kHSxGjeKtCA:buyq81s) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/PlayerViewController.swift#L45)):*
> ```Swift
>     
>     private func loadViews() {
> //        playerImage.moa.url = player.photoUrl
> ```

Why did we comment out the photo loading? Was it not working?
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 50 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhsdD81VWvWvVektCF:-LUpe8jf0ysfe-G7HHbT:b-vp4m1i) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L50)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

this was the issue I was talking about! I can't get the previous VC to pass the player object. 
</blockquote></details>

I'll help you out with this one today
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 97 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhtNAV80L2zNrXMzI5:-LUpf-57A3n7ruQftmRz:b4300wi) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L97)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it. 
</blockquote></details>

This comment is out of date. There was a todo here. Mark this as done if it's done
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 35 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlTPmoEKPKaxHkxeef:-LUpdwy0DE9rnlDWzdGo:b-97pwvk) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Good names. However, these are set scores, not match scores. Let’s renamed these set1LoserTextField etc. also, organize them from left to right (set1winner, set1loser, set2winner, etc)
</blockquote></details>

I think this one is out of date. Mark as done
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 23 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpdTsnDPYZ1ixgHuA0:-LUpdTso4PtCf5PMQ2_t:b-fgzpyk) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L23)):*
> ```Swift
>     
>     //MARK: Private Properties
>     private var possibleScores = Array(0...7)
> ```

Do we need to save this as a class variable? What is it used for?
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 24 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpddNTC9p9coB0pODL:-LUpddNTC9p9coB0pODM:bij07un) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L24)):*
> ```Swift
>     //MARK: Private Proper [...]

2018-12-28 16:46 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 41 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 73 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUht3tk8ljNPAczP3ix:-LUphTsNB8S-tDZ7t4IL:b-zas4o8) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L73)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Okay, I'll work on that today.
</blockquote></details>

Leave this open until you've finished it or have questions about it


<!-- Sent from Reviewable.io -->

2018-12-28 23:21 UTC, powerpufffs commented
___
*[TennisLadder/.DS_Store, line  at r4](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpBcenEHNeRxIsptVQ:-LUr6p6MAhxn3I1wFHQg:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/fe14270b696e4cfa7919c08c4c8ab1aaea221b1f/TennisLadder/.DS_Store#L)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

It looks like you added it to your gitignore properly, but you didn't git rm all the ones that were already committed. Can you do that? (when you're done, this file should be gone). Also, look for any others that might have been committed
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-28 23:21 UTC, powerpufffs reviewed
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 6 of 13 files reviewed, 41 unresolved discussions (waiting on @romrell4 and @powerpufffs)

___
*[Podfile, line 11 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhHNVd94e09mnF9K7a:-LUr6X__CSekBTodXs4T:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/Podfile#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Work with me on this one. It's working on master without it
</blockquote></details>

Done.
___
*[TennisLadder.xcodeproj/project.pbxproj, line 627 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI0qT9ZJcWmSA5Wth:-LUpbwdB4mlp-6SAlGT9:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L627)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This just optimizes the swift code when it compiles. We shouldn't need this. Remove it before marking this comment as done
</blockquote></details>

Done.
___
*[TennisLadder.xcodeproj/project.pbxproj, line 430 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkmYbj-WtZ6gxavbr9:-LUpbpnI3KcOpRF-gVmk:boijwe9) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder.xcodeproj/project.pbxproj#L430)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Uh oh. Is this something that we missed when renaming the project? Can this file get removed entirely? Search the rest of the this for files called just "Tennis" to see if we missed anything else
</blockquote></details>

Previous post on slack: There are also quite a few rogue “tennis” in the pbxproj file. About 3/4 were TennisLadder and the remaining being just Tennis. I’ve renamed all of them, but I didn’t touch any that were named Tennis___ like TennisTests, TennisUITests. Should those be renamed to TennisLadderTests and TennisLadderUITests?
___
*[TennisLadder.xcodeproj/project.pbxproj, line 637 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpcgR5AZo6xBDreTCI:-LUpjFyC-d1dDaZUJ1s-:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder.xcodeproj/project.pbxproj#L637)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

See above
</blockquote></details>

Done.
___
*[TennisLadder/Controller/PlayerViewController.swift, line 57 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkqm9p96kUAShmDt8D:-LUpjRbC-ds_lJzhygbc:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder/Controller/PlayerViewController.swift#L57)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This looks out of date. Mark this as done
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 28 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlSzq-0maOUCFogyye:-LUqKasgAZpFCGCudJDo:bqzinia) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L28)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we need to save these as well as the text fields? I thought we’d only need to save the text fields as Class level variables
</blockquote></details>

I can't think of a way to do without them. They need to be accessible to the didSelectRow method.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 23 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpdTsnDPYZ1ixgHuA0:-LUq0_0O7aUhtifkYCNK:bakwmca) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L23)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do we need to save this as a class variable? What is it used for?
</blockquote></details>

This is to store all the possible scores in the pickerView.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 144 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpfCeH2bMY1blm1Bo9:-LUpxDKz1XsDjCt9TG7S:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L144)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think you can just use self.dismiss. You don't have to call the presenting view controller
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 147 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpfNqm7ExKLaIUfkFa:-LUpxLEA34jjI3mcko0y:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L147)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think you can remove the completion entirely:
```
reportConfirmAlert.addAction(UIAlertAction(title: "No", style: .cancel)
```
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 153 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpfYK4ANle2nzcaFj7:-LUpxc4b-_0jvSsZCOEk:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L153)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

When done testing, remove print
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 157 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpfmxJ1IZ5aXSp4A-a:-LUpw0eyAxapvQccBKtY:bg2yt58) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L157)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think there might be an easier way to check this. Here's what I did on Android. See if you can figure out how to do the same in Swift:
```
val playedThirdSet = me_set3_picker.value != 0 || opponent_set3_picker.value != 0
val lastSetScore = if (playedThirdSet) me_set3_picker.value to opponent_set3_picker.value else me_set2_picker.value to opponent_set2_picker.value
val iWon = lastSetScore.first > lastSetScore.second
```
</blockquote></details>

Tried to do something similar. 
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 173 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpgCQG7sYOCf1wxikW:-LUptmvH0OnSi3f30j2T:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L173)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Our team's style guide has spaces between the `->` and return type. Reformat
</blockquote></details>

Done.
___
*[TennisLadder/View/MatchTableViewCell.swift, line 18 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkr3YdDNCzK2wXAXFN:-LUpnPur02mbNWcGfM6u:bpy96wu) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder/View/MatchTableViewCell.swift#L18)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i> [...]

2018-12-28 23:27 UTC, powerpufffs commented
___
*[TennisLadder.xcodeproj/project.pbxproj, line 617 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpcG567SrriLRW8jN-:-LUr89jWBrJC3K4Cgnf6:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder.xcodeproj/project.pbxproj#L617)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Was this added on purpose? Is there a reason why we need it?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-28 23:37 UTC, powerpufffs commented
___
*[TennisLadder/Controller/LadderViewController.swift, line 46 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhIiWf1OdT7eY1w2jW:-LUrAPyO5MwcTOHwplqu:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/LadderViewController.swift#L46)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Sounds good. Resolve before commenting again
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-29 00:14 UTC, powerpufffs reviewed
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 4 of 15 files reviewed, 41 unresolved discussions (waiting on @romrell4 and @powerpufffs)

___
*[TennisLadder/Controller/PlayerViewController.swift, line 73 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhL_ONCGmMVK6N_B-e:-LUrHZvJ2hx5fh7Sh2gx:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L73)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it :) 
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 12 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhrreg2ngsDFOro6u2:-LUrHc2GDUKuO08hCQWx:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Instead of the VC being the delegate, can we just use the textboxes with picker accessory views? I think there are a number of instances where we do this in the BYU app, so it would be good to learn how to do it :)
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 22 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhraaJAGEr6T7PY3z_:-LUrITl538k3F-DGKIMC:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Interesting. Mine always makes them weak. Let’s look at this tomorrow. You can google the difference between strong (default) and weak
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 50 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhsdD81VWvWvVektCF:-LUrIfaP1jFHLANRLoyh:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L50)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I'll help you out with this one today
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 73 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUht3tk8ljNPAczP3ix:-LUrIlTZAIjKQSzfotN_:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L73)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Leave this open until you've finished it or have questions about it
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 102 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhuFadAey4j5jOcguz:-LUrIpJmArpmwcja0_8k:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L102)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove exclamation point. In fact, you can change this whole callback into trailing closure syntax with an ignored parameter so that it looks like this: 
```
reportConfirmAction.addAction(UIAlertAction(title: "...", style: .default) { (_) in
  ...
})
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 103 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhu531DMHvp_sJ8ULK:-LUrIorb1AadiRQJB9_o:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L103)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it (talk to me if you have questions)
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 35 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlTPmoEKPKaxHkxeef:-LUrIYAL94ghNk0USB3H:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L35)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think this one is out of date. Mark as done
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 49 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlTrdO03Jn3zNa0YYv:-LUrIZLhErmWGFf_rxvN:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L49)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why do you pass this in if they’re already class level variables? Can’t you just do this in the function?
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 52 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlTzs48eINW-cDHwPv:-LUrIeOOBP_lXtigKuMO:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think there’s a way to do this without a gesture... let’s look at this tomorrow
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 23 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpdTsnDPYZ1ixgHuA0:-LUrHf1z3e_jo60kCR3p:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L23)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

This is to store all the possible scores in the pickerView.
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 24 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpddNTC9p9coB0pODL:-LUrHdtC-DmlqTKEnu_J:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L24)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Now that you have the newMatch variable, I don't think you need these anymore
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 31 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpdmeh0M3ykN6jSRoa:-LUrHgam6lpSCxXLzEdx:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L31)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I don't think you'll want this as an exclamation point. This will not always been set, right? Talk to me if you have questions
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 101 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpembD0Y3ryQWZctYb:-LUrImK-77yb3uY3Crmz:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController. [...]

2018-12-29 00:14 UTC, powerpufffs commented
___
*[TennisLadder/View/Base.lproj/Main.storyboard, line 691 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUph5dVEjEDkaD9KFqh:-LUrIxTz5i9zKFF-mQBf:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/View/Base.lproj/Main.storyboard#L691)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

I kept the old one as reference for the new one. It's deleted now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-29 00:15 UTC, romrell4 requested changes
> Reviewed 6 of 8 files at r6, 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 13 of 15 files reviewed, 28 unresolved discussions (waiting on @romrell4 and @powerpufffs)

___
*[TennisLadder.xcodeproj/project.pbxproj, line 430 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkmYbj-WtZ6gxavbr9:-LUrGj_C1kucQdDV-qej:b11kf7p) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder.xcodeproj/project.pbxproj#L430)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Previous post on slack: There are also quite a few rogue “tennis” in the pbxproj file. About 3/4 were TennisLadder and the remaining being just Tennis. I’ve renamed all of them, but I didn’t touch any that were named Tennis___ like TennisTests, TennisUITests. Should those be renamed to TennisLadderTests and TennisLadderUITests?
</blockquote></details>

I'll do this one. I'll submit a PR to you
___
*[TennisLadder/Controller/LadderViewController.swift, line 32 at r7](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrGy6M03Bbh0rtUg5w:-LUrGy6M03Bbh0rtUg5x:b4d8fpp) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/d97061f06357a043878e12555648115e1aa5e9b7/TennisLadder/Controller/LadderViewController.swift#L32)):*
> ```Swift
>                 self.players = players
>                 
>                 self.me = players.first { player in
> ```

Use shorthand
___
*[TennisLadder/Controller/PlayerViewController.swift, line 73 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhL_ONCGmMVK6N_B-e:-LUrH6yFCjnW6qQv2EI7:bdrrj4t) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/PlayerViewController.swift#L73)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it :) 
</blockquote></details>

I don't think this will be needed after removing the button altogether
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 23 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpdTsnDPYZ1ixgHuA0:-LUrHF-p1A1bmPCQOwE0:b-jeh1oj) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L23)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

This is to store all the possible scores in the pickerView.
</blockquote></details>

Still needed without picker views?
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 43 at r7](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrHQmD7cWssdOCX2hd:-LUrHQmD7cWssdOCX2he:b-hsqx2k) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/d97061f06357a043878e12555648115e1aa5e9b7/TennisLadder/Controller/ReportMatchViewController.swift#L43)):*
> ```Swift
>         super.viewDidLoad()
>         
>         newMatch = Match(matchId: nil,
> ```

Remove. Just put in when create the match to send
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 116 at r7](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrIYSt6OTrbgZJ0DBf:-LUrIYSt6OTrbgZJ0DBg:bnbdqs5) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/d97061f06357a043878e12555648115e1aa5e9b7/TennisLadder/Controller/ReportMatchViewController.swift#L116)):*
> ```Swift
> }
> 
> extension UITextField {
> ```

Now that you only use it twice, it probably doesn't make sense to have an extension anymore
___
*[TennisLadder/View/MatchTableViewCell.swift, line 18 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkr3YdDNCzK2wXAXFN:-LUrIsCvBwi6O-nRAPDu:b-ufmeli) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder/View/MatchTableViewCell.swift#L18)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Tried my best! Let me know if it needs changing.
</blockquote></details>

Looks pretty good! You and I did this together, and I think it should be moved into the Match object now...


<!-- Sent from Reviewable.io -->

2018-12-29 00:36 UTC, romrell4 requested changes
> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 16 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/PlayerViewController.swift, line 69 at r8](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrNwn79kY4GTk1gJtl:-LUrNwn79kY4GTk1gJtm:b-89817p) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/7aeea50a6ceda16c01cc4e6b16670c8a3010cd88/TennisLadder/Controller/PlayerViewController.swift#L69)):*
> ```Swift
>             let vc = segue.destination as? ReportMatchViewController {
>             
>             //TODO: Pass in correct Players
> ```

Do it
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 69 at r8](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrNduY2HKDtOOPvp-D:-LUrNduY2HKDtOOPvp-E:b-89817p) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/7aeea50a6ceda16c01cc4e6b16670c8a3010cd88/TennisLadder/Controller/ReportMatchViewController.swift#L69)):*
> ```Swift
>         reportConfirmAlert.addAction(UIAlertAction(title: "Yes", style: .default) { (_) in
> //            self.delegate.passNewMatch(match: self.newMatch)
>             
> ```

Do it
___
*[TennisLadder/Model/Endpoints.swift, line 59 at r8](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrNhdD3JCTZDkf5t96:-LUrNhdD3JCTZDkf5t97:br07uuq) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/7aeea50a6ceda16c01cc4e6b16670c8a3010cd88/TennisLadder/Model/Endpoints.swift#L59)):*
> ```Swift
> 	}
>     
>     func responseSingle<T: Decodable>(_ callback: @escaping (Response<T>) -> Void) {
> ```

Eric: Make this better


<!-- Sent from Reviewable.io -->

2018-12-29 00:36 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 16 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 42 at r8](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrO1IF1CRLyj9tNORz:-LUrO1IF1CRLyj9tNOS-:b-89817p) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/7aeea50a6ceda16c01cc4e6b16670c8a3010cd88/TennisLadder/Controller/ReportMatchViewController.swift#L42)):*
> ```Swift
>         super.viewDidLoad()
>         
>         //TODO: Auto select first textfield and have numpad pop up
> ```

Do it


<!-- Sent from Reviewable.io -->

2018-12-29 00:37 UTC, powerpufffs commented
___
*[TennisLadder/Controller/LadderViewController.swift, line 32 at r7](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrGy6M03Bbh0rtUg5w:-LUrOBJq76hhi9pvWSUh:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/d97061f06357a043878e12555648115e1aa5e9b7/TennisLadder/Controller/LadderViewController.swift#L32)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Use shorthand
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-29 00:37 UTC, powerpufffs reviewed
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 14 of 15 files reviewed, 16 unresolved discussions (waiting on @romrell4 and @powerpufffs)

___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 19 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhrSIF4AUVyCWkJwRB:-LUrJN0e7We-hWTUJS04:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

What do you mean by that? You should have a ladder (the player objects know which ladderId they are in)
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 97 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhtNAV80L2zNrXMzI5:-LUrJhOtCdfZHWxc0SDM:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L97)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This comment is out of date. There was a todo here. Mark this as done if it's done
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 28 at r3](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUlSzq-0maOUCFogyye:-LUrJOdQB_zLzAfCp2ym:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/38902b431bbf1c984d87a6e25b7cd15e1b83b11b/TennisLadder/Controller/ReportMatchViewController.swift#L28)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

I can't think of a way to do without them. They need to be accessible to the didSelectRow method.
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 63 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpeBgt1bukG4Fc-0sd:-LUrJYhV26bDDeVo_2GC:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/ReportMatchViewController.swift#L63)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Did we comment this all out because the player isn't being passed in properly yet? If so, let's get it working again today. Either way, leave this comment open until we get it resolved
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 43 at r7](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrHQmD7cWssdOCX2hd:-LUrJWDVEOnSGf2ZY73w:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/d97061f06357a043878e12555648115e1aa5e9b7/TennisLadder/Controller/ReportMatchViewController.swift#L43)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove. Just put in when create the match to send
</blockquote></details>

Done.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 116 at r7](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrIYSt6OTrbgZJ0DBf:-LUrNlas1jCBo15R09qG:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/d97061f06357a043878e12555648115e1aa5e9b7/TennisLadder/Controller/ReportMatchViewController.swift#L116)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Now that you only use it twice, it probably doesn't make sense to have an extension anymore
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-29 00:38 UTC, romrell4 requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 12 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 19 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhrSIF4AUVyCWkJwRB:-LUrOReF5WjTDuYNnbWe:bfhqmln) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder/Controller/ReportMatchViewController.swift#L19)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not done?


<!-- Sent from Reviewable.io -->

2018-12-29 00:40 UTC, powerpufffs commented
___
*[TennisLadder/Controller/PlayerViewController.swift, line 45 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpd3hE8kHSxGjeKtC9:-LUrOpp_-TsH5xSPkxAr:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/PlayerViewController.swift#L45)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why did we comment out the photo loading? Was it not working?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-29 00:41 UTC, romrell4 reviewed
> Reviewed 1 of 1 files at r10.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 10 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/PlayerViewController.swift, line 45 at r5](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUpd3hE8kHSxGjeKtC9:-LUrOw5DAF7Je1IxmJxP:b7orp7g) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/86e4bc14a0957f84ed45b980596284b19deeb2eb/TennisLadder/Controller/PlayerViewController.swift#L45)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why is this commented out?


<!-- Sent from Reviewable.io -->

2018-12-29 00:42 UTC, romrell4 reviewed
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 10 unresolved discussions (waiting on @powerpufffs)



<!-- Sent from Reviewable.io -->

2018-12-29 00:44 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 11 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/View/MatchTableViewCell.swift, line 13 at r11](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrPsYe2VYac-UEkDih:-LUrPsYfB3_3FimvqBXa:bvxi224) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/cbf6d2e2281fda5ee3fd95f360cc75edad335aa3/TennisLadder/View/MatchTableViewCell.swift#L13)):*
> ```Swift
> class MatchTableViewCell: UITableViewCell {
>     @IBOutlet private weak var matchLabel: UILabel!
>     @IBOutlet private weak var recordLabel: UILabel!
> ```

this should be a `scoreLabel` instead


<!-- Sent from Reviewable.io -->

2018-12-29 02:06 UTC, romrell4 requested changes
> Reviewed 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 11 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 100 at r12](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrhXMv2M_XfK9JgLLe:-LUrhXMv2M_XfK9JgLLf:b-89817p) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/bb340e7f6757240faa6211b58ef82011edca54af/TennisLadder/Controller/ReportMatchViewController.swift#L100)):*
> ```Swift
>             .filter { $0.0 != "" && $0.1 != "" }
>         
>         //TODO: Move this logic into the match object
> ```

Do it
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 107 at r12](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrhWSF9KsS7Z5NvXcZ:-LUrhWSF9KsS7Z5NvXc_:b-89817p) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/bb340e7f6757240faa6211b58ef82011edca54af/TennisLadder/Controller/ReportMatchViewController.swift#L107)):*
> ```Swift
>     
>     private func getMatch() -> Match {
>         //TODO: Fill in newMatch with proper values
> ```

Do it


<!-- Sent from Reviewable.io -->

2018-12-29 17:55 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 10 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder.xcodeproj/project.pbxproj, line 619 at r1](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUhI83qAj1rFquPuv-k:-LUv3r_FA3P8XhGrAmjK:bemlqcs) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/4d0d0615c9656253e3b6346eeaeedac2f2b95439/TennisLadder.xcodeproj/project.pbxproj#L619)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

It still looks unchanged. The code on master has `G9JN5J3VZ9`. Work with me on this one
</blockquote></details>

Just revert this right before we merge. Leave open until then


<!-- Sent from Reviewable.io -->

2018-12-29 17:56 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 10 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder.xcodeproj/project.pbxproj, line 430 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkmYbj-WtZ6gxavbr9:-LUv5t-Z2UoKMBnbhqTB:bdf0d8b) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder.xcodeproj/project.pbxproj#L430)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I'll do this one. I'll submit a PR to you
</blockquote></details>

Just submitted it. Once you finish that review, we'll merge it into this branch and mark this as done


<!-- Sent from Reviewable.io -->

2018-12-29 18:07 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 11 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/LadderViewController.swift, line 27 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv8_W48G_UH96lZpyl:-LUv8_W48G_UH96lZpym:bshk2ag) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/Controller/LadderViewController.swift#L27)):*
> ```Swift
>         super.viewDidLoad()
>         
>         Endpoints.getPlayers(ladder.ladderId).response { (response: Response<[Player]>) in
> ```

Add swipe to refresh on table view


<!-- Sent from Reviewable.io -->

2018-12-29 18:11 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 14 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/LadderViewController.swift, line 79 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv8ivy63RSO908CnYA:-LUv8ivy63RSO908CnYB:b-qgb8rf) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/Controller/LadderViewController.swift#L79)):*
> ```Swift
>     }
>     
>     @IBAction func reportMatchTapped(_ sender: Any) {
> ```

Change toolbar color. I'm starting to wonder if the Android blue color would look good...
___
*[TennisLadder/View/MatchTableViewCell.swift, line 12 at r12](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv8wKABJk8ElJ3ZkbQ:-LUv8wKABJk8ElJ3ZkbR:b-rbopas) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/bb340e7f6757240faa6211b58ef82011edca54af/TennisLadder/View/MatchTableViewCell.swift#L12)):*
> ```Swift
> 
> class MatchTableViewCell: UITableViewCell {
>     @IBOutlet private weak var matchLabel: UILabel!
> ```

Rename this to opponentNameLabel
___
*[TennisLadder/View/MatchTableViewCell.swift, line 19 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv9-HN2xa6S6Mih1u7:-LUv9-HN2xa6S6Mih1u8:bm9i9n7) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/View/MatchTableViewCell.swift#L19)):*
> ```Swift
>             
>             //TODO: Rename recordLabel
>             matchLabel.text = "\(match.matchId)"
> ```

We don't want to display the matchId here. Android displays the opponent's name I believe


<!-- Sent from Reviewable.io -->

2018-12-29 18:26 UTC, romrell4 reviewed
> Reviewed 6 of 6 files at r14.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 13 unresolved discussions (waiting on @powerpufffs)



<!-- Sent from Reviewable.io -->

2018-12-29 21:02 UTC, romrell4 requested changes
> Reviewed 5 of 5 files at r15.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 14 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/View/MatchTableViewCell.swift, line 11 at r15](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUvlJyH6yD9M0qlEsAn:-LUvlJyH6yD9M0qlEsAo:blyscs) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/480e5796481ad1b30b3b20a4157313e663842780/TennisLadder/View/MatchTableViewCell.swift#L11)):*
> ```Swift
> import UIKit
> 
> class MatchTableViewCell: UITableViewCell {
> ```

In the storyboard, this definitely doesn't need its own stack view. The right detail style should do everything we need


<!-- Sent from Reviewable.io -->

2018-12-29 23:53 UTC, romrell4 requested changes
> Reviewed 4 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 15 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/PlayerViewController.swift, line 22 at r16](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwNVku9Jdeu35sS4p2:-LUwNVku9Jdeu35sS4p3:bh33lxb) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/49140d5158e4afed756f2836348eac2f35ca4717/TennisLadder/Controller/PlayerViewController.swift#L22)):*
> ```Swift
>     @IBOutlet private weak var playerImage: UIImageView!
>     @IBOutlet private weak var currentRankingLabel: UILabel!
>     @IBOutlet private weak var setsLabel: UILabel!
> ```

Why did we change this? This is supposed to be the recordLabel still... Did you change the wrong one?


<!-- Sent from Reviewable.io -->

2018-12-30 01:06 UTC, powerpufffs commented
___
*[TennisLadder/Controller/LadderViewController.swift, line 79 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv8ivy63RSO908CnYA:-LUwbE6M2QIkPTiycDSL:brnoqth) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/Controller/LadderViewController.swift#L79)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Change toolbar color. I'm starting to wonder if the Android blue color would look good...
</blockquote></details>

Done. I looked up the color online and this is what I got: #4169E1


<!-- Sent from Reviewable.io -->

2018-12-30 01:06 UTC, powerpufffs commented
___
*[TennisLadder/Controller/LadderViewController.swift, line 27 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv8_W48G_UH96lZpyl:-LUwZbvR4aHDSDo57TRE:b-o92ql0) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/Controller/LadderViewController.swift#L27)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Add swipe to refresh on table view
</blockquote></details>

Tried my best! Did you want this also in the playerVC so that they can reload the tableview in there for the matches as well?


<!-- Sent from Reviewable.io -->

2018-12-30 01:12 UTC, powerpufffs commented
___
*[TennisLadder/Controller/PlayerViewController.swift, line 22 at r16](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwNVku9Jdeu35sS4p2:-LUweZB-6uHZVJvkd-Sb:b92ffaf) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/49140d5158e4afed756f2836348eac2f35ca4717/TennisLadder/Controller/PlayerViewController.swift#L22)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Why did we change this? This is supposed to be the recordLabel still... Did you change the wrong one?
</blockquote></details>

Done. I think that it was fine the way it was originally...just had a TODO that should have been removed yesterday.


<!-- Sent from Reviewable.io -->

2018-12-30 01:30 UTC, powerpufffs commented
___
*[TennisLadder/View/MatchTableViewCell.swift, line 11 at r15](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUvlJyH6yD9M0qlEsAn:-LUwiZqKAPVfeFdmdbgl:b2tnept) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/480e5796481ad1b30b3b20a4157313e663842780/TennisLadder/View/MatchTableViewCell.swift#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

In the storyboard, this definitely doesn't need its own stack view. The right detail style should do everything we need
</blockquote></details>

Removed the stack view and put constraints instead. 


<!-- Sent from Reviewable.io -->

2018-12-30 01:33 UTC, powerpufffs commented
___
*[TennisLadder/View/MatchTableViewCell.swift, line 12 at r12](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv8wKABJk8ElJ3ZkbQ:-LUwj_zA4VQHJbOr8w8_:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/bb340e7f6757240faa6211b58ef82011edca54af/TennisLadder/View/MatchTableViewCell.swift#L12)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Rename this to opponentNameLabel
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-30 01:33 UTC, powerpufffs commented
___
*[TennisLadder/View/MatchTableViewCell.swift, line 13 at r11](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrPsYe2VYac-UEkDih:-LUwjatU9xEyOZiyeJ9_:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/cbf6d2e2281fda5ee3fd95f360cc75edad335aa3/TennisLadder/View/MatchTableViewCell.swift#L13)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

this should be a `scoreLabel` instead
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-30 01:36 UTC, powerpufffs commented
___
*[TennisLadder/View/MatchTableViewCell.swift, line 19 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv9-HN2xa6S6Mih1u7:-LUwjuqN8iOVi2n1A6jM:b-qcvw0b) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/View/MatchTableViewCell.swift#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

We don't want to display the matchId here. Android displays the opponent's name I believe
</blockquote></details>

the match Id doesn't contain a the name of the player. Should I instantiate a player variable in the file? Or should I code logic to figure out who won so that it knows whether to put winner.name or loser.name?


<!-- Sent from Reviewable.io -->

2018-12-30 01:47 UTC, powerpufffs commented
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 100 at r12](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrhXMv2M_XfK9JgLLe:-LUwmaCw69-YHHk7b_G3:b-5uy8w9) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/bb340e7f6757240faa6211b58ef82011edca54af/TennisLadder/Controller/ReportMatchViewController.swift#L100)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

For this one, should I have a separate var lastSet in the Match struct? If so, I'd need to copy the code to get the array of sets. Is there a better way than that? I'd need to add set as a variable to the struct, and I don't know whether that will interfere with the ajax call or not....


<!-- Sent from Reviewable.io -->

2018-12-30 02:10 UTC, romrell4 requested changes
> Reviewed 5 of 5 files at r17, 1 of 1 files at r18.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 15 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/LadderViewController.swift, line 79 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv8ivy63RSO908CnYA:-LUwrMq6-HPJuKotf1Mz:b-e8nm7z) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/Controller/LadderViewController.swift#L79)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Done. I looked up the color online and this is what I got: #4169E1
</blockquote></details>

Here's the right one: `#3f51b5`
___
*[TennisLadder/Controller/LadderViewController.swift, line 48 at r17](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwpv138-bqJdeyQ8yd:-LUwpv138-bqJdeyQ8ye:be6jrpr) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/67b82ddc15af30e49c9dabf629fd95305edc7051/TennisLadder/Controller/LadderViewController.swift#L48)):*
> ```Swift
>     private func addRefreshControl() {
>         let swipeRefreshControl = UIRefreshControl()
>         swipeRefreshControl.attributedTitle = NSAttributedString(string: "swipe up to refresh")
> ```

This title is misleading. They don't need to swipe up to refresh. Let's have this say "Refreshing..."
___
*[TennisLadder/Controller/LadderViewController.swift, line 51 at r17](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwqMzR5ABbXz1yjEw9:-LUwqMzR5ABbXz1yjEwA:b-tjjc68) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/67b82ddc15af30e49c9dabf629fd95305edc7051/TennisLadder/Controller/LadderViewController.swift#L51)):*
> ```Swift
>         swipeRefreshControl.addTarget(self, action: #selector(refreshTableView), for: .valueChanged)
>         
>         if #available(iOS 10.0, *) {
> ```

I think we're targeting iOS 11, so you don't need this line. Just use the tableView.refreshControl one
___
*[TennisLadder/Controller/LadderViewController.swift, line 58 at r17](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwq2--3oiS3nB9yzqM:-LUwq2--3oiS3nB9yzqN:b-l3fulw) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/67b82ddc15af30e49c9dabf629fd95305edc7051/TennisLadder/Controller/LadderViewController.swift#L58)):*
> ```Swift
>     }
>     
>     @objc private func refreshTableView() {
> ```

Let's just name this loadPlayers() and call it from the viewDidLoad as well to remove the duplicate logic
___
*[TennisLadder/Controller/LadderViewController.swift, line 71 at r17](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwq9FW8AcFaJUwdeNI:-LUwq9FW8AcFaJUwdeNJ:bfolct5) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/67b82ddc15af30e49c9dabf629fd95305edc7051/TennisLadder/Controller/LadderViewController.swift#L71)):*
> ```Swift
>             }
>         }
>         self.tableView.refreshControl?.endRefreshing()
> ```

This line should be inside of the callback (probably right before `switch response`. Otherwise, it stops the refreshing spinner before the data is actually refreshed.
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 42 at r8](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrO1IF1CRLyj9tNORz:-LUwrXpI0hyR1oY3ZHQb:b-7vi346) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/7aeea50a6ceda16c01cc4e6b16670c8a3010cd88/TennisLadder/Controller/ReportMatchViewController.swift#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

It looks like you did this one. Did you forget to remove this TODO?
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 100 at r12](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrhXMv2M_XfK9JgLLe:-LUwrpqF-DAKFb4kjvRp:b94ku73) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/bb340e7f6757240faa6211b58ef82011edca54af/TennisLadder/Controller/ReportMatchViewController.swift#L100)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

For this one, should I have a separate var lastSet in the Match struct? If so, I'd need to copy the code to get the array of sets. Is there a better way than that? I'd need to add set as a variable to the struct, and I don't know whether that will interfere with the ajax call or not....
</blockquote></details>

Let's chat about this one next time I'm in... I think creating a computed var for lastSet would work
___
*[TennisLadder/View/MatchTableViewCell.swift, line 19 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv9-HN2xa6S6Mih1u7:-LUwp_ErD9uvvdagWjG7:bobutvb) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/View/MatchTableViewCell.swift#L19)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

the match Id doesn't contain a the name of the player. Should I instantiate a player variable in the file? Or should I code logic to figure out who won so that it knows whether to put winner.name or loser.name?
</blockquote></details>

Yup. Let me give you some Android code:
```
listOf(match.winner, match.loser).first { it.userId != player.userId }.name
```
___
*[TennisLadder/View/MatchTableViewCell.swift, line 11 at r15](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUvlJyH6yD9M0qlEsAn:-LUwpNjPDjCFoMnxGx-7:b-7zmjx1) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/480e5796481ad1b30b3b20a4157313e663842780/TennisLadder/View/MatchTableViewCell.swift#L11)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Removed the stack view and put constraints instead. 
</blockquote></details>

I don't even think you need that. Just switch to the "Right Detail" style, and it should give you a textView and detailTextView that look just like we want.


<!-- Sent from Reviewable.io -->

2018-12-30 02:38 UTC, powerpufffs commented
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 42 at r8](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrO1IF1CRLyj9tNORz:-LUwxCpb5hZmdTpEktbt:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/7aeea50a6ceda16c01cc4e6b16670c8a3010cd88/TennisLadder/Controller/ReportMatchViewController.swift#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

It looks like you did this one. Did you forget to remove this TODO?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-30 02:39 UTC, powerpufffs commented
___
*[TennisLadder/Controller/PlayerViewController.swift, line 73 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkrAWa1ghE-VsblaFu:-LUwybEc2-H5Y46umUNc:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder/Controller/PlayerViewController.swift#L73)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I like the idea of the delegate! Gratefully, we can do this with an unwind segue. I'll talk to you about this one. However, this is also a very good way of doing it!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-30 02:39 UTC, powerpufffs commented
___
*[TennisLadder/Controller/PlayerViewController.swift, line 42 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkqLpS7NWRryK4CYLL:-LUwycP1-h5nx-TghaPO:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder/Controller/PlayerViewController.swift#L42)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Great. We'll still see if we can replace this with unwind segues. Google around to learn what unwind segues are, and let me know if you have any questions. I can help you with this today if you'd like
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-30 02:40 UTC, powerpufffs commented
___
*[TennisLadder/Controller/LadderViewController.swift, line 51 at r17](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwqMzR5ABbXz1yjEw9:-LUwyvPm0nUf65mDJdRD:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/67b82ddc15af30e49c9dabf629fd95305edc7051/TennisLadder/Controller/LadderViewController.swift#L51)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think we're targeting iOS 11, so you don't need this line. Just use the tableView.refreshControl one
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-30 02:42 UTC, powerpufffs commented
___
*[TennisLadder/Controller/LadderViewController.swift, line 48 at r17](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwpv138-bqJdeyQ8yd:-LUwz0Z61VkpQ8dzESa5:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/67b82ddc15af30e49c9dabf629fd95305edc7051/TennisLadder/Controller/LadderViewController.swift#L48)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This title is misleading. They don't need to swipe up to refresh. Let's have this say "Refreshing..."
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-30 02:44 UTC, powerpufffs commented
___
*[TennisLadder/Controller/LadderViewController.swift, line 58 at r17](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwq2--3oiS3nB9yzqM:-LUwzjgSDuZgZOhFVJ8W:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/67b82ddc15af30e49c9dabf629fd95305edc7051/TennisLadder/Controller/LadderViewController.swift#L58)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's just name this loadPlayers() and call it from the viewDidLoad as well to remove the duplicate logic
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-30 04:29 UTC, romrell4 requested changes
> Reviewed 4 of 4 files at r19.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 13 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/LadderViewController.swift, line 48 at r17](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwpv138-bqJdeyQ8yd:-LUxLpI-54XbNkEQpUlW:b-dvxs1v) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/67b82ddc15af30e49c9dabf629fd95305edc7051/TennisLadder/Controller/LadderViewController.swift#L48)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Remove the `=`
___
*[TennisLadder/Controller/LadderViewController.swift, line 71 at r17](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwq9FW8AcFaJUwdeNI:-LUxLwjD5OhG2R498Pea:b-gc91ry) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/67b82ddc15af30e49c9dabf629fd95305edc7051/TennisLadder/Controller/LadderViewController.swift#L71)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This line should be inside of the callback (probably right before `switch response`. Otherwise, it stops the refreshing spinner before the data is actually refreshed.
</blockquote></details>

This looks done. Did you mean to "done" this one?
___
*[TennisLadder/Controller/LadderViewController.swift, line 114 at r19](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUxM3YsCwREaHG45WKs:-LUxM3YsCwREaHG45WKt:b-nvggc3) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/92fdd680605f99cd2156a0806080059609c31d76/TennisLadder/Controller/LadderViewController.swift#L114)):*
> ```Swift
>         players.forEach { player in
>             alert.addAction(UIAlertAction(title: player.name, style: .default) { (_) in
>                 self.performSegue(withIdentifier: "matchReported", sender: player)
> ```

Was this a bug? Did you mean to change this?
___
*[TennisLadder/Controller/PlayerViewController.swift, line 42 at r2](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUkqLpS7NWRryK4CYLL:-LUxMKFZDRKut_l8pUpM:b-vqy0mr) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/98db8d0fa81f6f09f23017cf9fe4cd32c5065944/TennisLadder/Controller/PlayerViewController.swift#L42)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done? Did you get the unwind segue working already?
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 52 at r19](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUxMPNj1W26-_05ULr6:-LUxMPNj1W26-_05ULr7:b-3tyzia) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/92fdd680605f99cd2156a0806080059609c31d76/TennisLadder/Controller/ReportMatchViewController.swift#L52)):*
> ```Swift
> 
>     private func setUpViews() {
>         //TODO: Player objects still aren't being pass through properly. Find out why these are unwrapping nil
> ```

Do it (I can help you next week)
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 69 at r19](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUxMTOA378-ECkcykYz:-LUxMTOA378-ECkcykZ-:b-aqfzki) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/92fdd680605f99cd2156a0806080059609c31d76/TennisLadder/Controller/ReportMatchViewController.swift#L69)):*
> ```Swift
>             Endpoints.reportMatch(match.ladderId, match).responseSingle { (response: Response<Match>) in
>                 switch response {
>                     case .success(let matchSuccess):
> ```

Name this `match` again. `matchSuccess` doesn't make sense. You shouldn't need to set the match on the next line either. In fact, you don't even have to save the match anywhere. Just dismiss
___
*[TennisLadder/View/Base.lproj/Main.storyboard, line 322 at r19](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUxMmc64AFQjcJTZZ7u:-LUxMmc64AFQjcJTZZ7v:b-si2ra7) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/92fdd680605f99cd2156a0806080059609c31d76/TennisLadder/View/Base.lproj/Main.storyboard#L322)):*
> ```XML
>                                 </constraints>
>                             </stackView>
>                             <tableView clipsSubviews="YES" contentMode="scaleToFill" ambiguous="YES" alwaysBounceVertical="YES" dataMode="prototypes" style="plain" separatorStyle="default" rowHeight="-1" estimatedRowHeight="-1" sectionHeaderHeight="28" sectionFooterHeight="28" translatesAutoresizingMaskIntoConstraints="NO" id="cs1-PK-uKF">
> ```

I think this means that your tableview doesn't have the correct constraints now that you removed the toolbar. Make sure you have a bottom constraint


<!-- Sent from Reviewable.io -->

2018-12-30 21:57 UTC, romrell4 reviewed
> Reviewed 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 13 unresolved discussions (waiting on @powerpufffs)



<!-- Sent from Reviewable.io -->

2018-12-30 22:06 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 14 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/View/PlayerCell.swift, line 11 at r20](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV08jXF-MSRNuN30Vj7:-LV08jXF-MSRNuN30Vj8:bfehlj7) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/af95bf552ff529f0f776355593d7ae4293cd488b/TennisLadder/View/PlayerCell.swift#L11)):*
> ```Swift
> import UIKit
> 
> class PlayerCell: UITableViewCell {
> ```

Can this be renamed to PlayerTableViewCell (for consistency with the other ones)


<!-- Sent from Reviewable.io -->

2018-12-30 22:50 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 15 unresolved discussions (waiting on @powerpufffs)

*[a discussion](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV0IyBq5dtMM20J5msZ:-LV0IyBrDZF8occNDtuc:b-dzuajr) (no related file):*
Remind me to look over your Xcode settings with you (indentation is off)

---


<!-- Sent from Reviewable.io -->

2018-12-30 22:59 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 18 unresolved discussions (waiting on @powerpufffs)

*[a discussion](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV0JkPw0uqnvQzWuycn:-LV0JkPw0uqnvQzWuyco:b-9g9hwh) (no related file):*
Let's add a navigation bar to the modal view controller by embedded it in it's own navigation controller. Talk to me if you have questions

---
*[a discussion](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV0K-Dp7pwC99Mjl1Up:-LV0K-Dp7pwC99Mjl1Uq:b-v55cjl) (no related file):*
Let's change the background color of the PlayerVC's main view to #eeeeee. I think it looks a little bit better than having everything be white.

---
*[a discussion](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV0KVJxCKrLoC7lbZsp:-LV0KVJxCKrLoC7lbZsq:b-86f1dh) (no related file):*
Change the ReportMatchVC button to have the same text as Android (and talk to me about the button. I don't really like the colors of our buttons right now)

---


<!-- Sent from Reviewable.io -->

2018-12-31 17:36 UTC, powerpufffs commented
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 69 at r19](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUxMTOA378-ECkcykYz:-LV4KZqM6FS1axTHu0Bg:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/92fdd680605f99cd2156a0806080059609c31d76/TennisLadder/Controller/ReportMatchViewController.swift#L69)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Name this `match` again. `matchSuccess` doesn't make sense. You shouldn't need to set the match on the next line either. In fact, you don't even have to save the match anywhere. Just dismiss
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-31 17:38 UTC, romrell4 reviewed
> Reviewed 1 of 1 files at r21.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 17 unresolved discussions (waiting on @powerpufffs)



<!-- Sent from Reviewable.io -->

2018-12-31 17:54 UTC, powerpufffs commented
___
*[TennisLadder/View/MatchTableViewCell.swift, line 11 at r15](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUvlJyH6yD9M0qlEsAn:-LV4L0a9-vZiqT6c169x:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/480e5796481ad1b30b3b20a4157313e663842780/TennisLadder/View/MatchTableViewCell.swift#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I don't even think you need that. Just switch to the "Right Detail" style, and it should give you a textView and detailTextView that look just like we want.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-31 17:55 UTC, powerpufffs commented
___
*[TennisLadder/View/PlayerCell.swift, line 11 at r20](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV08jXF-MSRNuN30Vj7:-LV4OxhF4q1txj4nA3g7:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/af95bf552ff529f0f776355593d7ae4293cd488b/TennisLadder/View/PlayerCell.swift#L11)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Can this be renamed to PlayerTableViewCell (for consistency with the other ones)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-31 17:59 UTC, powerpufffs commented
___
*[TennisLadder/View/Base.lproj/Main.storyboard, line 322 at r19](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUxMmc64AFQjcJTZZ7u:-LV4PpZZ2WYOl49wzfe6:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/92fdd680605f99cd2156a0806080059609c31d76/TennisLadder/View/Base.lproj/Main.storyboard#L322)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think this means that your tableview doesn't have the correct constraints now that you removed the toolbar. Make sure you have a bottom constraint
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-31 18:01 UTC, powerpufffs commented
___
*[TennisLadder/Controller/LadderViewController.swift, line 48 at r17](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwpv138-bqJdeyQ8yd:-LV4QDDKAgFpvxVFfFID:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/67b82ddc15af30e49c9dabf629fd95305edc7051/TennisLadder/Controller/LadderViewController.swift#L48)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remove the `=`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-31 18:03 UTC, powerpufffs commented
___
*[TennisLadder/Controller/LadderViewController.swift, line 114 at r19](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUxM3YsCwREaHG45WKs:-LV4QhGY4V0KiI07ALnk:bwoq5bq) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/92fdd680605f99cd2156a0806080059609c31d76/TennisLadder/Controller/LadderViewController.swift#L114)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Was this a bug? Did you mean to change this?
</blockquote></details>

Yep! I was calling another segue by accident.


<!-- Sent from Reviewable.io -->

2018-12-31 18:24 UTC, powerpufffs commented
___
*[TennisLadder/View/MatchTableViewCell.swift, line 19 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv9-HN2xa6S6Mih1u7:-LV4VWFK9qDE6IDf5NtK:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/View/MatchTableViewCell.swift#L19)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Yup. Let me give you some Android code:
```
listOf(match.winner, match.loser).first { it.userId != player.userId }.name
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-31 18:26 UTC, romrell4 requested changes
> Reviewed 3 of 8 files at r24, 3 of 3 files at r25, 3 of 4 files at r26, 4 of 4 files at r27.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 12 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/PlayerViewController.swift, line 64 at r27](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV4W-O8AVXhXf4D56Z3:-LV4W-O8AVXhXf4D56Z4:b-1yvy5c) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/e06a48888b1bd77060ebaf1ab0c381e76c681541/TennisLadder/Controller/PlayerViewController.swift#L64)):*
> ```Swift
> 		
> 		cell.textLabel?.text = [match.winner, match.loser].first { $0.userId != player.userId }?.name
> 		//TODO: Display from player's perspective
> ```

I think this is done
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 107 at r12](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrhWSF9KsS7Z5NvXcZ:-LV4VaevA08v9htfCEU_:bfz3hu8) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/bb340e7f6757240faa6211b58ef82011edca54af/TennisLadder/Controller/ReportMatchViewController.swift#L107)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

Android code:
```
private fun getMatch(): Match {
		val playedThirdSet = me_set3_score.getIntOrNull() != null && opponent_set3_score.getIntOrNull() != null
		val lastSetScore = if (playedThirdSet) me_set3_score.getInt() to opponent_set3_score.getInt() else me_set2_score.getInt() to opponent_set2_score.getInt()
		val iWon = lastSetScore.first > lastSetScore.second

		return Match(
			ladderId = me.ladderId,
			winner = if (iWon) me else opponent,
			loser = if (iWon) opponent else me,
			winnerSet1Score = (if (iWon) me_set1_score else opponent_set1_score).getInt(),
			loserSet1Score = (if (iWon) opponent_set1_score else me_set1_score).getInt(),
			winnerSet2Score = (if (iWon) me_set2_score else opponent_set2_score).getInt(),
			loserSet2Score = (if (iWon) opponent_set2_score else me_set2_score).getInt()
		).apply {
			if (playedThirdSet) {
				winnerSet3Score = (if (iWon) me_set3_score else opponent_set3_score).getInt()
				loserSet3Score = (if (iWon) opponent_set3_score else me_set3_score).getInt()
			}
		}
	}

```


<!-- Sent from Reviewable.io -->

2018-12-31 18:26 UTC, powerpufffs reviewed
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 12 unresolved discussions (waiting on @powerpufffs and @romrell4)

___
*[TennisLadder/Controller/LadderViewController.swift, line 71 at r17](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUwq9FW8AcFaJUwdeNI:-LUx-3C644yONl0SghQH:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/67b82ddc15af30e49c9dabf629fd95305edc7051/TennisLadder/Controller/LadderViewController.swift#L71)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

This line should be inside of the callback (probably right before `switch response`. Otherwise, it stops the refreshing spinner before the data is actually refreshed.
</blockquote></details>

Done.
___
*[TennisLadder/Controller/PlayerViewController.swift, line 69 at r8](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrNwn79kY4GTk1gJtl:-LV4QvSZ81JDfX7ad7Ws:b-kakxbt) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/7aeea50a6ceda16c01cc4e6b16670c8a3010cd88/TennisLadder/Controller/PlayerViewController.swift#L69)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

I think I forgot to mark this as done before.


<!-- Sent from Reviewable.io -->

2018-12-31 18:27 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 11 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/LadderViewController.swift, line 79 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv8ivy63RSO908CnYA:-LV4WFo6CeWuFV57a71I:bfhcj3g) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/Controller/LadderViewController.swift#L79)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Here's the right one: `#3f51b5`
</blockquote></details>

Is this done?


<!-- Sent from Reviewable.io -->

2018-12-31 19:05 UTC, powerpufffs commented
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 107 at r12](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrhWSF9KsS7Z5NvXcZ:-LV4e16D9FkF8oTBCf4d:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/bb340e7f6757240faa6211b58ef82011edca54af/TennisLadder/Controller/ReportMatchViewController.swift#L107)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Android code:
```
private fun getMatch(): Match {
		val playedThirdSet = me_set3_score.getIntOrNull() != null && opponent_set3_score.getIntOrNull() != null
		val lastSetScore = if (playedThirdSet) me_set3_score.getInt() to opponent_set3_score.getInt() else me_set2_score.getInt() to opponent_set2_score.getInt()
		val iWon = lastSetScore.first > lastSetScore.second

		return Match(
			ladderId = me.ladderId,
			winner = if (iWon) me else opponent,
			loser = if (iWon) opponent else me,
			winnerSet1Score = (if (iWon) me_set1_score else opponent_set1_score).getInt(),
			loserSet1Score = (if (iWon) opponent_set1_score else me_set1_score).getInt(),
			winnerSet2Score = (if (iWon) me_set2_score else opponent_set2_score).getInt(),
			loserSet2Score = (if (iWon) opponent_set2_score else me_set2_score).getInt()
		).apply {
			if (playedThirdSet) {
				winnerSet3Score = (if (iWon) me_set3_score else opponent_set3_score).getInt()
				loserSet3Score = (if (iWon) opponent_set3_score else me_set3_score).getInt()
			}
		}
	}

```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-31 19:07 UTC, romrell4 requested changes
> Reviewed 2 of 2 files at r28.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 11 unresolved discussions (waiting on @powerpufffs)

___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 108 at r28](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV4eJ0eC7TgCOeY6y2t:-LV4eJ0eC7TgCOeY6y2u:b-ow7pje) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/172d0552d0d9c06194cf3ee7531c3072c08bf889/TennisLadder/Controller/ReportMatchViewController.swift#L108)):*
> ```Swift
> 
> extension UITextField {
> 	func toInt() -> Int {
> ```

Make private


<!-- Sent from Reviewable.io -->

2018-12-31 19:08 UTC, powerpufffs commented
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 100 at r12](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrhXMv2M_XfK9JgLLe:-LV4eY0A7h-uh2plzy0W:bf91hhg) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/bb340e7f6757240faa6211b58ef82011edca54af/TennisLadder/Controller/ReportMatchViewController.swift#L100)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's chat about this one next time I'm in... I think creating a computed var for lastSet would work
</blockquote></details>

Done. Removed the generate message function entirely.


<!-- Sent from Reviewable.io -->

2018-12-31 19:09 UTC, powerpufffs commented
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 52 at r19](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUxMPNj1W26-_05ULr6:-LV4etCW2XKiFkktVCuX:b-ykyvex) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/92fdd680605f99cd2156a0806080059609c31d76/TennisLadder/Controller/ReportMatchViewController.swift#L52)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it (I can help you next week)
</blockquote></details>

Done. It's working now.


<!-- Sent from Reviewable.io -->

2018-12-31 19:09 UTC, powerpufffs commented
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 69 at r8](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrNduY2HKDtOOPvp-D:-LV4ex295fIv1XJ10DJ3:b-tr6jow) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/7aeea50a6ceda16c01cc4e6b16670c8a3010cd88/TennisLadder/Controller/ReportMatchViewController.swift#L69)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Do it
</blockquote></details>

I think I forgot to mark this one as done.


<!-- Sent from Reviewable.io -->

2018-12-31 19:10 UTC, powerpufffs commented
___
*[TennisLadder/Controller/PlayerViewController.swift, line 64 at r27](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV4W-O8AVXhXf4D56Z3:-LV4f1wy60-tFx8Be8kp:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/e06a48888b1bd77060ebaf1ab0c381e76c681541/TennisLadder/Controller/PlayerViewController.swift#L64)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

I think this is done
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-31 19:10 UTC, powerpufffs commented
___
*[TennisLadder/Controller/LadderViewController.swift, line 79 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv8ivy63RSO908CnYA:-LV4f5tEC_mn4_zn_KNs:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/Controller/LadderViewController.swift#L79)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Is this done?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-31 19:10 UTC, powerpufffs commented
*[a discussion](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV0IyBq5dtMM20J5msZ:-LV4fFC4DXELszSLNRLq:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Remind me to look over your Xcode settings with you (indentation is off)
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2018-12-31 19:12 UTC, powerpufffs commented
*[a discussion](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV0K-Dp7pwC99Mjl1Up:-LV4fV0X9e2yXINR0IT7:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's change the background color of the PlayerVC's main view to #eeeeee. I think it looks a little bit better than having everything be white.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2018-12-31 19:23 UTC, powerpufffs reviewed
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 12 of 14 files reviewed, 11 unresolved discussions (waiting on @romrell4 and @powerpufffs)

*[a discussion](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV0JkPw0uqnvQzWuycn:-LV4iBM0BQ_h0clSga6D:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Let's add a navigation bar to the modal view controller by embedded it in it's own navigation controller. Talk to me if you have questions
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2018-12-31 19:33 UTC, romrell4 reviewed
> Reviewed 4 of 4 files at r29.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 7 unresolved discussions (waiting on @powerpufffs and @romrell4)

___
*[TennisLadder/Controller/LadderViewController.swift, line 79 at r13](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUv8ivy63RSO908CnYA:-LV4jh8X2f0x2PT3mYJZ:b-287p5k) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/a1bc9d70f4cc28300f1e82c1e12d3dea95a88995/TennisLadder/Controller/LadderViewController.swift#L79)):*
<details><summary><i>Previously, powerpufffs (Isaac Z Tai) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still work with me on this one. I think we can make it look better


<!-- Sent from Reviewable.io -->

2018-12-31 19:41 UTC, powerpufffs reviewed
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @romrell4 and @powerpufffs)

___
*[TennisLadder/Model/Endpoints.swift, line 59 at r8](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LUrNhdD3JCTZDkf5t96:-LV4mDwF3MzAG8yfqziD:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/7aeea50a6ceda16c01cc4e6b16670c8a3010cd88/TennisLadder/Model/Endpoints.swift#L59)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Eric: Make this better
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-31 19:43 UTC, romrell4 reviewed
> Reviewed 2 of 2 files at r30.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 3 unresolved discussions (waiting on @powerpufffs)



<!-- Sent from Reviewable.io -->

2018-12-31 19:50 UTC, powerpufffs commented
___
*[TennisLadder/Controller/ReportMatchViewController.swift, line 108 at r28](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV4eJ0eC7TgCOeY6y2t:-LV4o8S41wcZXD4YKJbV:b-896fix) ([raw file](https://github.com/romrell4/tennis-ladder-ios/blob/172d0552d0d9c06194cf3ee7531c3072c08bf889/TennisLadder/Controller/ReportMatchViewController.swift#L108)):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Make private
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-12-31 20:01 UTC, powerpufffs commented
*[a discussion](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4#-LV0KVJxCKrLoC7lbZsp:-LV4qisMEUUFWMCQ4qt9:b-896fix) (no related file):*
<details><summary><i>Previously, romrell4 (Eric Romrell) wrote…</i></summary><blockquote>

Change the ReportMatchVC button to have the same text as Android (and talk to me about the button. I don't really like the colors of our buttons right now)
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2018-12-31 20:16 UTC, romrell4 reviewed
> Reviewed 4 of 4 files at r31.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @romrell4 and @powerpufffs)



<!-- Sent from Reviewable.io -->

2018-12-31 20:17 UTC, romrell4 reviewed
> Reviewed 2 of 2 files at r32.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: all files reviewed, 1 unresolved discussion (waiting on @powerpufffs)



<!-- Sent from Reviewable.io -->

2018-12-31 20:22 UTC, romrell4 approved these changes
> Reviewed 3 of 3 files at r33.
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-12-31 20:22 UTC, romrell4 approved these changes
> *[Reviewable](https://reviewable.io/reviews/romrell4/tennis-ladder-ios/4)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2018-12-31 20:22 UTC, merged